services:
  api:
    build: .
    container_name: inventory-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:admin@postgres:5432/inventory
      PORT: 3000

  postgres:
    image: postgres:15
    container_name: inventory-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inventory